apiVersion: v1
kind: Service
metadata:
    name: "toasites-6619"
    labels:
        app: "toasites-6619"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "toasites-6619"