on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: toarepository.azurecr.io
          username: ${{ secrets.acr_toarepository_username }}
          password: ${{ secrets.acr_toarepository_password }}

      - name: Build and push image to ACR
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t toarepository.azurecr.io/toasites:${{ github.sha }}
          docker push toarepository.azurecr.io/toasites:${{ github.sha }}

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_toasites_kubeConfig }}
        id: login

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep toasites88a6 | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace toasites88a6`
          fi

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: toasites88a6
          container-registry-url: toarepository.azurecr.io
          container-registry-username: ${{ secrets.acr_toarepository_username }}
          container-registry-password: ${{ secrets.acr_toarepository_password }}
          secret-name: toasitesdockerauth

      - uses: azure/k8s-deploy@v1
        with:
          namespace: toasites88a6
          manifests: |
            manifests/deployment-1.yml
            manifests/service-1.yml
          images: |
            toarepository.azurecr.io/toasites:${{ github.sha }}
          imagepullsecrets: |
            toasitesdockerauth
